/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LookingForRouteImport } from './routes/looking-for'
import { Route as LeaseAnalysisRouteImport } from './routes/lease-analysis'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FindMyMatchRouteImport } from './routes/find-my-match'
import { Route as CampusesRouteImport } from './routes/campuses'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedIndexRouteImport } from './routes/saved.index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as SubleaseSlugRouteImport } from './routes/sublease.$slug'
import { Route as SavedCollectionRouteImport } from './routes/saved.$collection'
import { Route as RoommatesCreateRouteImport } from './routes/roommates.create'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as MessagesConversationIdRouteImport } from './routes/messages.$conversationId'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AmbassadorDashboardRouteImport } from './routes/ambassador_.dashboard'
import { Route as PostEditIdRouteImport } from './routes/post.edit.$id'
import { Route as MyListingsListingIdAnalyticsRouteImport } from './routes/my-listings.$listingId.analytics'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ListingIdEditRouteImport } from './routes/listing.$id_.edit'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksListingExpiryRemindersRouteImport } from './routes/api/public/hooks/listing-expiry-reminders'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LookingForRoute = LookingForRouteImport.update({
  id: '/looking-for',
  path: '/looking-for',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseAnalysisRoute = LeaseAnalysisRouteImport.update({
  id: '/lease-analysis',
  path: '/lease-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyMatchRoute = FindMyMatchRouteImport.update({
  id: '/find-my-match',
  path: '/find-my-match',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusesRoute = CampusesRouteImport.update({
  id: '/campuses',
  path: '/campuses',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedIndexRoute = SavedIndexRouteImport.update({
  id: '/saved/',
  path: '/saved/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubleaseSlugRoute = SubleaseSlugRouteImport.update({
  id: '/sublease/$slug',
  path: '/sublease/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedCollectionRoute = SavedCollectionRouteImport.update({
  id: '/saved/$collection',
  path: '/saved/$collection',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesCreateRoute = RoommatesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RoommatesRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const MessagesConversationIdRoute = MessagesConversationIdRouteImport.update({
  id: '/messages/$conversationId',
  path: '/messages/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorDashboardRoute = AmbassadorDashboardRouteImport.update({
  id: '/ambassador_/dashboard',
  path: '/ambassador/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PostEditIdRoute = PostEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => PostRoute,
} as any)
const MyListingsListingIdAnalyticsRoute =
  MyListingsListingIdAnalyticsRouteImport.update({
    id: '/$listingId/analytics',
    path: '/$listingId/analytics',
    getParentRoute: () => MyListingsRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdEditRoute = ListingIdEditRouteImport.update({
  id: '/listing/$id_/edit',
  path: '/listing/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksListingExpiryRemindersRoute =
  ApiPublicHooksListingExpiryRemindersRouteImport.update({
    id: '/api/public/hooks/listing-expiry-reminders',
    path: '/api/public/hooks/listing-expiry-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/campuses': typeof CampusesRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ambassador/dashboard': typeof AmbassadorDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/saved/$collection': typeof SavedCollectionRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/messages/': typeof MessagesIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/post/edit/$id': typeof PostEditIdRoute
  '/api/public/hooks/listing-expiry-reminders': typeof ApiPublicHooksListingExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/campuses': typeof CampusesRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ambassador/dashboard': typeof AmbassadorDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/saved/$collection': typeof SavedCollectionRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/messages': typeof MessagesIndexRoute
  '/saved': typeof SavedIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/listing/$id/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/post/edit/$id': typeof PostEditIdRoute
  '/api/public/hooks/listing-expiry-reminders': typeof ApiPublicHooksListingExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/campuses': typeof CampusesRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/ambassador_/dashboard': typeof AmbassadorDashboardRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/listing/$id': typeof ListingIdRoute
  '/messages/$conversationId': typeof MessagesConversationIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/saved/$collection': typeof SavedCollectionRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/messages/': typeof MessagesIndexRoute
  '/saved/': typeof SavedIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/listing/$id_/edit': typeof ListingIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/post/edit/$id': typeof PostEditIdRoute
  '/api/public/hooks/listing-expiry-reminders': typeof ApiPublicHooksListingExpiryRemindersRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/campuses'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/ambassador/dashboard'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/roommates/create'
    | '/saved/$collection'
    | '/sublease/$slug'
    | '/messages/'
    | '/saved/'
    | '/api/public/stripe-webhook'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/post/edit/$id'
    | '/api/public/hooks/listing-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/campuses'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/ambassador/dashboard'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/roommates/create'
    | '/saved/$collection'
    | '/sublease/$slug'
    | '/messages'
    | '/saved'
    | '/api/public/stripe-webhook'
    | '/listing/$id/edit'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/post/edit/$id'
    | '/api/public/hooks/listing-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/campuses'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/ambassador_/dashboard'
    | '/email/unsubscribe'
    | '/listing/$id'
    | '/messages/$conversationId'
    | '/profile/$userId'
    | '/profile/edit'
    | '/roommates/create'
    | '/saved/$collection'
    | '/sublease/$slug'
    | '/messages/'
    | '/saved/'
    | '/api/public/stripe-webhook'
    | '/listing/$id_/edit'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/post/edit/$id'
    | '/api/public/hooks/listing-expiry-reminders'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AmbassadorRoute: typeof AmbassadorRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CampusesRoute: typeof CampusesRoute
  FindMyMatchRoute: typeof FindMyMatchRoute
  JoinRoute: typeof JoinRoute
  LeaseAnalysisRoute: typeof LeaseAnalysisRoute
  LookingForRoute: typeof LookingForRoute
  MarketRoute: typeof MarketRoute
  MyListingsRoute: typeof MyListingsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PostRoute: typeof PostRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  RoommatesRoute: typeof RoommatesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursRoute: typeof ToursRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AmbassadorDashboardRoute: typeof AmbassadorDashboardRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ListingIdRoute: typeof ListingIdRoute
  MessagesConversationIdRoute: typeof MessagesConversationIdRoute
  SavedCollectionRoute: typeof SavedCollectionRoute
  SubleaseSlugRoute: typeof SubleaseSlugRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  SavedIndexRoute: typeof SavedIndexRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ListingIdEditRoute: typeof ListingIdEditRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksListingExpiryRemindersRoute: typeof ApiPublicHooksListingExpiryRemindersRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looking-for': {
      id: '/looking-for'
      path: '/looking-for'
      fullPath: '/looking-for'
      preLoaderRoute: typeof LookingForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease-analysis': {
      id: '/lease-analysis'
      path: '/lease-analysis'
      fullPath: '/lease-analysis'
      preLoaderRoute: typeof LeaseAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-match': {
      id: '/find-my-match'
      path: '/find-my-match'
      fullPath: '/find-my-match'
      preLoaderRoute: typeof FindMyMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campuses': {
      id: '/campuses'
      path: '/campuses'
      fullPath: '/campuses'
      preLoaderRoute: typeof CampusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/': {
      id: '/saved/'
      path: '/saved'
      fullPath: '/saved/'
      preLoaderRoute: typeof SavedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sublease/$slug': {
      id: '/sublease/$slug'
      path: '/sublease/$slug'
      fullPath: '/sublease/$slug'
      preLoaderRoute: typeof SubleaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved/$collection': {
      id: '/saved/$collection'
      path: '/saved/$collection'
      fullPath: '/saved/$collection'
      preLoaderRoute: typeof SavedCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates/create': {
      id: '/roommates/create'
      path: '/create'
      fullPath: '/roommates/create'
      preLoaderRoute: typeof RoommatesCreateRouteImport
      parentRoute: typeof RoommatesRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/messages/$conversationId': {
      id: '/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof MessagesConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador_/dashboard': {
      id: '/ambassador_/dashboard'
      path: '/ambassador/dashboard'
      fullPath: '/ambassador/dashboard'
      preLoaderRoute: typeof AmbassadorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/edit/$id': {
      id: '/post/edit/$id'
      path: '/edit/$id'
      fullPath: '/post/edit/$id'
      preLoaderRoute: typeof PostEditIdRouteImport
      parentRoute: typeof PostRoute
    }
    '/my-listings/$listingId/analytics': {
      id: '/my-listings/$listingId/analytics'
      path: '/$listingId/analytics'
      fullPath: '/my-listings/$listingId/analytics'
      preLoaderRoute: typeof MyListingsListingIdAnalyticsRouteImport
      parentRoute: typeof MyListingsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id_/edit': {
      id: '/listing/$id_/edit'
      path: '/listing/$id/edit'
      fullPath: '/listing/$id/edit'
      preLoaderRoute: typeof ListingIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/listing-expiry-reminders': {
      id: '/api/public/hooks/listing-expiry-reminders'
      path: '/api/public/hooks/listing-expiry-reminders'
      fullPath: '/api/public/hooks/listing-expiry-reminders'
      preLoaderRoute: typeof ApiPublicHooksListingExpiryRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MyListingsRouteChildren {
  MyListingsListingIdAnalyticsRoute: typeof MyListingsListingIdAnalyticsRoute
}

const MyListingsRouteChildren: MyListingsRouteChildren = {
  MyListingsListingIdAnalyticsRoute: MyListingsListingIdAnalyticsRoute,
}

const MyListingsRouteWithChildren = MyListingsRoute._addFileChildren(
  MyListingsRouteChildren,
)

interface PostRouteChildren {
  PostEditIdRoute: typeof PostEditIdRoute
}

const PostRouteChildren: PostRouteChildren = {
  PostEditIdRoute: PostEditIdRoute,
}

const PostRouteWithChildren = PostRoute._addFileChildren(PostRouteChildren)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RoommatesRouteChildren {
  RoommatesCreateRoute: typeof RoommatesCreateRoute
}

const RoommatesRouteChildren: RoommatesRouteChildren = {
  RoommatesCreateRoute: RoommatesCreateRoute,
}

const RoommatesRouteWithChildren = RoommatesRoute._addFileChildren(
  RoommatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AmbassadorRoute: AmbassadorRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CampusesRoute: CampusesRoute,
  FindMyMatchRoute: FindMyMatchRoute,
  JoinRoute: JoinRoute,
  LeaseAnalysisRoute: LeaseAnalysisRoute,
  LookingForRoute: LookingForRoute,
  MarketRoute: MarketRoute,
  MyListingsRoute: MyListingsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PostRoute: PostRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  RoommatesRoute: RoommatesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursRoute: ToursRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AmbassadorDashboardRoute: AmbassadorDashboardRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ListingIdRoute: ListingIdRoute,
  MessagesConversationIdRoute: MessagesConversationIdRoute,
  SavedCollectionRoute: SavedCollectionRoute,
  SubleaseSlugRoute: SubleaseSlugRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  SavedIndexRoute: SavedIndexRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ListingIdEditRoute: ListingIdEditRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksListingExpiryRemindersRoute:
    ApiPublicHooksListingExpiryRemindersRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
