/**
 * Router bootstrap. TanStack Start calls getRouter() per request on the server
 * (each SSR request gets its own QueryClient — no cross-request leakage) and
 * once on the client at hydration.
 *
 * - routeTree is auto-generated by the @tanstack/router-plugin Vite plugin
 *   from files in src/routes/. Do NOT edit src/routeTree.gen.ts by hand.
 * - context.queryClient is consumed by route loaders via
 *     context.queryClient.ensureQueryData(...)
 *   This is our canonical data-loading pattern; do not use useEffect+fetch.
 * - defaultPreloadStaleTime: 0 forces preloads to refetch fresh data; we
 *   rely on TanStack Query's own caching for dedupe.
 */
import { QueryClient, dehydrate, hydrate, type DehydratedState } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const getRouter = () => {
  const queryClient = new QueryClient();

  const router = createRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
    // Q471 — hand the server's query cache to the browser. Without this the
    // client starts with an EMPTY cache, so the first client render of any
    // query-backed text (the footer's campus links, counts, rails) differs
    // from the server HTML and React throws #418 and re-renders the whole
    // page, discarding our SSR output.
    // TanStack types the dehydrated payload against a Serializable check that
    // React Query's own DehydratedState (whose `data` is `unknown`) can never
    // satisfy. The payload is serialized with seroval, which handles Map/Set/
    // Date fine — the values here are plain query results and Maps.
    // @ts-expect-error -- DehydratedState.data is `unknown`; serialization is safe.
    dehydrate: () => ({
      queryState: dehydrate(queryClient, { shouldDehydrateMutation: () => false }),
    }),
    hydrate: (dehydrated: { queryState: DehydratedState }) => {
      hydrate(queryClient, dehydrated.queryState);
    },
  });

  return router;
};
