/**
 * Router bootstrap. TanStack Start calls getRouter() per request on the server
 * (each SSR request gets its own QueryClient — no cross-request leakage) and
 * once on the client at hydration.
 *
 * - routeTree is auto-generated by the @tanstack/router-plugin Vite plugin
 *   from files in src/routes/. Do NOT edit src/routeTree.gen.ts by hand.
 * - context.queryClient is consumed by route loaders via
 *     context.queryClient.ensureQueryData(...)
 *   This is our canonical data-loading pattern; do not use useEffect+fetch.
 * - defaultPreloadStaleTime: 0 forces preloads to refetch fresh data; we
 *   rely on TanStack Query's own caching for dedupe.
 */
import { QueryClient } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const getRouter = () => {
  const queryClient = new QueryClient();

  const router = createRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
  });

  return router;
};
