/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostRouteImport } from './routes/post'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyListingsRouteImport } from './routes/my-listings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LookingForRouteImport } from './routes/looking-for'
import { Route as LeaseAnalysisRouteImport } from './routes/lease-analysis'
import { Route as JoinRouteImport } from './routes/join'
import { Route as FindMyMatchRouteImport } from './routes/find-my-match'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubleaseSlugRouteImport } from './routes/sublease.$slug'
import { Route as RoommatesCreateRouteImport } from './routes/roommates.create'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as MessagesListingIdRouteImport } from './routes/messages.$listingId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as MyListingsListingIdAnalyticsRouteImport } from './routes/my-listings.$listingId.analytics'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRoute = PostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsRoute = MyListingsRouteImport.update({
  id: '/my-listings',
  path: '/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LookingForRoute = LookingForRouteImport.update({
  id: '/looking-for',
  path: '/looking-for',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaseAnalysisRoute = LeaseAnalysisRouteImport.update({
  id: '/lease-analysis',
  path: '/lease-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const FindMyMatchRoute = FindMyMatchRouteImport.update({
  id: '/find-my-match',
  path: '/find-my-match',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubleaseSlugRoute = SubleaseSlugRouteImport.update({
  id: '/sublease/$slug',
  path: '/sublease/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesCreateRoute = RoommatesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RoommatesRoute,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ProfileRoute,
} as any)
const MessagesListingIdRoute = MessagesListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MessagesRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListingsListingIdAnalyticsRoute =
  MyListingsListingIdAnalyticsRouteImport.update({
    id: '/$listingId/analytics',
    path: '/$listingId/analytics',
    getParentRoute: () => MyListingsRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRouteWithChildren
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/messages/$listingId': typeof MessagesListingIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRouteWithChildren
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/messages/$listingId': typeof MessagesListingIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/ambassador': typeof AmbassadorRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/find-my-match': typeof FindMyMatchRoute
  '/join': typeof JoinRoute
  '/lease-analysis': typeof LeaseAnalysisRoute
  '/looking-for': typeof LookingForRoute
  '/market': typeof MarketRoute
  '/messages': typeof MessagesRouteWithChildren
  '/my-listings': typeof MyListingsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/post': typeof PostRoute
  '/profile': typeof ProfileRouteWithChildren
  '/roommates': typeof RoommatesRouteWithChildren
  '/saved': typeof SavedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tours': typeof ToursRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/messages/$listingId': typeof MessagesListingIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/roommates/create': typeof RoommatesCreateRoute
  '/sublease/$slug': typeof SubleaseSlugRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/my-listings/$listingId/analytics': typeof MyListingsListingIdAnalyticsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/saved'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/messages/$listingId'
    | '/profile/$userId'
    | '/roommates/create'
    | '/sublease/$slug'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/saved'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/messages/$listingId'
    | '/profile/$userId'
    | '/roommates/create'
    | '/sublease/$slug'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/alerts'
    | '/ambassador'
    | '/auth'
    | '/browse'
    | '/find-my-match'
    | '/join'
    | '/lease-analysis'
    | '/looking-for'
    | '/market'
    | '/messages'
    | '/my-listings'
    | '/notifications'
    | '/onboarding'
    | '/post'
    | '/profile'
    | '/roommates'
    | '/saved'
    | '/sitemap.xml'
    | '/tours'
    | '/unsubscribe'
    | '/email/unsubscribe'
    | '/messages/$listingId'
    | '/profile/$userId'
    | '/roommates/create'
    | '/sublease/$slug'
    | '/api/public/stripe-webhook'
    | '/lovable/email/suppression'
    | '/my-listings/$listingId/analytics'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AmbassadorRoute: typeof AmbassadorRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  FindMyMatchRoute: typeof FindMyMatchRoute
  JoinRoute: typeof JoinRoute
  LeaseAnalysisRoute: typeof LeaseAnalysisRoute
  LookingForRoute: typeof LookingForRoute
  MarketRoute: typeof MarketRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  MyListingsRoute: typeof MyListingsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PostRoute: typeof PostRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  RoommatesRoute: typeof RoommatesRouteWithChildren
  SavedRoute: typeof SavedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ToursRoute: typeof ToursRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  SubleaseSlugRoute: typeof SubleaseSlugRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings': {
      id: '/my-listings'
      path: '/my-listings'
      fullPath: '/my-listings'
      preLoaderRoute: typeof MyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looking-for': {
      id: '/looking-for'
      path: '/looking-for'
      fullPath: '/looking-for'
      preLoaderRoute: typeof LookingForRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lease-analysis': {
      id: '/lease-analysis'
      path: '/lease-analysis'
      fullPath: '/lease-analysis'
      preLoaderRoute: typeof LeaseAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-my-match': {
      id: '/find-my-match'
      path: '/find-my-match'
      fullPath: '/find-my-match'
      preLoaderRoute: typeof FindMyMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sublease/$slug': {
      id: '/sublease/$slug'
      path: '/sublease/$slug'
      fullPath: '/sublease/$slug'
      preLoaderRoute: typeof SubleaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates/create': {
      id: '/roommates/create'
      path: '/create'
      fullPath: '/roommates/create'
      preLoaderRoute: typeof RoommatesCreateRouteImport
      parentRoute: typeof RoommatesRoute
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/messages/$listingId': {
      id: '/messages/$listingId'
      path: '/$listingId'
      fullPath: '/messages/$listingId'
      preLoaderRoute: typeof MessagesListingIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-listings/$listingId/analytics': {
      id: '/my-listings/$listingId/analytics'
      path: '/$listingId/analytics'
      fullPath: '/my-listings/$listingId/analytics'
      preLoaderRoute: typeof MyListingsListingIdAnalyticsRouteImport
      parentRoute: typeof MyListingsRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesListingIdRoute: typeof MessagesListingIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesListingIdRoute: MessagesListingIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface MyListingsRouteChildren {
  MyListingsListingIdAnalyticsRoute: typeof MyListingsListingIdAnalyticsRoute
}

const MyListingsRouteChildren: MyListingsRouteChildren = {
  MyListingsListingIdAnalyticsRoute: MyListingsListingIdAnalyticsRoute,
}

const MyListingsRouteWithChildren = MyListingsRoute._addFileChildren(
  MyListingsRouteChildren,
)

interface ProfileRouteChildren {
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileUserIdRoute: ProfileUserIdRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface RoommatesRouteChildren {
  RoommatesCreateRoute: typeof RoommatesCreateRoute
}

const RoommatesRouteChildren: RoommatesRouteChildren = {
  RoommatesCreateRoute: RoommatesCreateRoute,
}

const RoommatesRouteWithChildren = RoommatesRoute._addFileChildren(
  RoommatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AmbassadorRoute: AmbassadorRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  FindMyMatchRoute: FindMyMatchRoute,
  JoinRoute: JoinRoute,
  LeaseAnalysisRoute: LeaseAnalysisRoute,
  LookingForRoute: LookingForRoute,
  MarketRoute: MarketRoute,
  MessagesRoute: MessagesRouteWithChildren,
  MyListingsRoute: MyListingsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PostRoute: PostRoute,
  ProfileRoute: ProfileRouteWithChildren,
  RoommatesRoute: RoommatesRouteWithChildren,
  SavedRoute: SavedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ToursRoute: ToursRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  SubleaseSlugRoute: SubleaseSlugRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
